config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :articles
  root 'welcome#home'
  get 'about', to: 'welcome#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
	validates :title, presence: true, length: { minimun: 3, maximum: 10 }
	validates :description, presence: true, length: { minimun: 5, maximum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ActionController::Base
	def new
		@article = Article.new
	end

	def create
		# render plain: params[:article].inspect
		@article = Article.new(article_params)
		@article.save
		redirect_to articles_show(@article)
	end

	private
	def article_params
		params.require(:article).permit(:title, :description)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def home
		
	end

	def about
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/new.html.erb
<h1>Create new article.</h1>

<%=	form_for @article do |f| %>
	<p>
		<%= f.label :title %><br/>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :description %><br/>
		<%= f.text_area :description %>
	</p>

	<p>
		<%= f.submit %><br/>
	</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/about.html.erb
<h1>About Page.</h1>

<%= link_to 'Home', root_path %>

app/views/welcome/home.html.erb
<h1>This is home page</h1>

<%= link_to 'about', about_path %>

app/views/welcome/index.html.erb
<h1>This is home page</h1>